// <auto-generated />
using System;
using DCA_Padel_Club.Infrastructure.EfcDomainModelPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCA_Padel_Club.Infrastructure.EfcDomainModelPersistence.Migrations
{
    [DbContext(typeof(EfcDbContext))]
    [Migration("20260510140024_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("DCA_Padel_Club.Core.Domain.Aggregates.Players.Player", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Blacklisted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CooldownExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuarantineEndDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("BookingId");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("bookerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BookerId");

                    b.Property<string>("courtNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CourtNumber");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.BookingPlayerReference", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PlayerId");

                    b.HasKey("BookingId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("BookingPlayers", (string)null);
                });

            modelBuilder.Entity("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.Booking", b =>
                {
                    b.HasOne("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.Schedule", null)
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.BookingSlot", "bookingTimeSlot", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("TEXT")
                                .HasColumnName("SlotDate");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("SlotEndTime");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("SlotStartTime");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("bookingTimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.BookingPlayerReference", b =>
                {
                    b.HasOne("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.Booking", null)
                        .WithMany("playerIds")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCA_Padel_Club.Core.Domain.Aggregates.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.Schedule", b =>
                {
                    b.OwnsMany("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.PadelCourt", "Courts", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .HasColumnType("TEXT")
                                .HasColumnName("CourtNumber");

                            b1.Property<bool>("isOccupied")
                                .HasColumnType("INTEGER")
                                .HasColumnName("IsOccupied");

                            b1.HasKey("ScheduleId", "Number");

                            b1.ToTable("ScheduleCourts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("Courts");
                });

            modelBuilder.Entity("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.Booking", b =>
                {
                    b.Navigation("playerIds");
                });

            modelBuilder.Entity("DCA_Padel_Club.Core.Domain.Aggregates.Schedules.Schedule", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
